### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by tbqwk** [msorens/SqlDiffFramework#3]
Could not load file or assembly 'TaubererDiffEngine, Version1.0.0.0, Culture= neutral, PublicKeyToken=null' or one of its dependencies.  The system cannot find the file specified.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'TaubererDiffEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'TaubererDiffEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at SqlDiffFramework.Forms.MainForm.DiffDGV()
   at SqlDiffFramework.Forms.MainForm.sqlEditor_ExecuteQueryFinish(Object sender, EventArg`1 e)
   at CleanCode.SqlEditorControls.SqlEditor.OnExecuteQueryFinish(Boolean success)
   at CleanCode.SqlEditorControls.SqlEditor.RefreshGrid(Boolean forceUserPick)
   at CleanCode.SqlEditorControls.SqlEditor.DoExecute()
   at CleanCode.SqlEditorControls.SqlEditor.executeQueryButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.PerformClick()
   at CleanCode.SqlEditorControls.SqlEditor.PerformExecuteQuery()
   at SqlDiffFramework.Forms.MainForm.executeQueryMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8669 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
SqlDiffFramework
    Assembly Version: 1.0.4.0
    Win32 Version: 1.0.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/SqlDiffFramework/SqlDiffFramework.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5491 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8759 (QFE.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5495 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
CleanCode.GeneralComponents
    Assembly Version: 1.2.1.0
    Win32 Version: 1.2.01
    CodeBase: file:///C:/Program%20Files%20(x86)/SqlDiffFramework/CleanCode.GeneralComponents.DLL
----------------------------------------
CleanCode
    Assembly Version: 1.2.1.0
    Win32 Version: 1.2.01
    CodeBase: file:///C:/Program%20Files%20(x86)/SqlDiffFramework/CleanCode.DLL
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8773 (QFE.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
CleanCode.SqlEditorControls
    Assembly Version: 1.2.1.0
    Win32 Version: 1.2.01
    CodeBase: file:///C:/Program%20Files%20(x86)/SqlDiffFramework/CleanCode.SqlEditorControls.DLL
----------------------------------------
CleanCode.DatabaseControls
    Assembly Version: 1.2.1.0
    Win32 Version: 1.2.01
    CodeBase: file:///C:/Program%20Files%20(x86)/SqlDiffFramework/CleanCode.DatabaseControls.DLL
----------------------------------------
CleanCode.DataGridViewControls
    Assembly Version: 1.2.1.0
    Win32 Version: 1.2.01
    CodeBase: file:///C:/Program%20Files%20(x86)/SqlDiffFramework/CleanCode.DataGridViewControls.DLL
----------------------------------------
CleanCode.ChameleonRichTextBoxControls
    Assembly Version: 1.2.1.0
    Win32 Version: 1.2.01
    CodeBase: file:///C:/Program%20Files%20(x86)/SqlDiffFramework/CleanCode.ChameleonRichTextBoxControls.DLL
----------------------------------------
SyntaxHighlightingTextBox
    Assembly Version: 1.1.3935.32718
    Win32 Version: 1.1.3935.32718
    CodeBase: file:///C:/Program%20Files%20(x86)/SqlDiffFramework/SyntaxHighlightingTextBox.DLL
----------------------------------------
SearchableControls
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/SqlDiffFramework/SearchableControls.DLL
----------------------------------------
System.Core
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.5420 built by: Win7SP1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Data
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8751 (QFE.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Management
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8758 (QFE.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Management/2.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
VDialog
    Assembly Version: 1.4.3937.35378
    Win32 Version: 1.4.3937.35378
    CodeBase: file:///C:/Program%20Files%20(x86)/SqlDiffFramework/VDialog.DLL
----------------------------------------
mppcripc
    Assembly Version: 1.2.1.0
    Win32 Version: 2.0.50727.8759 (QFE.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
MySql.Data
    Assembly Version: 5.2.3.0
    Win32 Version: 5.2.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/SqlDiffFramework/MySql.Data.DLL
----------------------------------------
System.Data.OracleClient
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_32/System.Data.OracleClient/2.0.0.0__b77a5c561934e089/System.Data.OracleClient.dll
----------------------------------------
System.Transactions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_32/System.Transactions/2.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_32/System.EnterpriseServices/2.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by clementratel** [comment]
Hi,

I solved this one by downloading the ZIP of the source code then extract it and then copy Tauberersomething.DLL to the SqlDiffFramework Folder.
Then you are good to go, only I had to select "Potter" in Diff menu to see comparison start then switch back to Tauberer to have it (I guess it is the better since it is the default). You see the progress in the bottom left.

a+,=)
-=Clement=-

SQLDiffFramework v1.0.4.0
Windows 7 Pro
SQL Server 2008
SQL Server 2016 SP2
